# Generated by Django 3.1.7 on 2021-03-31 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=150, verbose_name='اسم اتاق')),
                ('members', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='اعضای گروه ')),
            ],
        ),
    ]
